name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: npm install & build
      run: |
        npm install
        npm run build

    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: dist/
        GH_PAT: ${{ secrets.GH_PAT }}
